


class Trajectory():
    """
    This class is for paring and operating with .trr files generated by Gromacs software
    """
    def __init__(self):
        pass

    def from_file(self):
        pass


class Logs():
    """
    This class is for parsing md.log files generated by Gromacs software
    """
    pass